[project]
name = "tortoise"
description = "tortoise"
version = "0.0.0"
dependencies = []
[[project.authors]]
name = "tortoise"
email = "tortoise@tortoise.com"

[tool.setuptools]
py-modules = ["tortoise"]
