[project]
name = "kaia"
description = "Kitchen assistant with face, voice and personality of your favorite character"
version = "0.0.0"
dependencies = [ ]
[[project.authors]]
name = "Yuri Okulovsky"
email = "yuri.okulovsky@gmail.com"

[tool.setuptools.packages.find]
where = ["."]
